name: API Test on Pull Request to Develop

on:
  pull_request:
    branches: [ develop ]

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: newman run "https://api.getpostman.com/collections/30943573-8015969f-095c-4330-ad0e-5d45b7c512c6?apikey=${{ secrets.POSTMAN_API_KEY }}"
